import Head from "next/head";
import { Swiper, SwiperSlide } from "swiper/react";
import React, { useEffect, useRef, useState } from "react";
import { Navigation } from "swiper";
import Image from "next/image";
import axios from "./api/axios";
import "swiper/css";
import "swiper/css/navigation";

import styled from "styled-components";
const StyleElement = styled.div`
  & .swiper-slide {
    font-size: 18px;
    background: #fff;
    display: flex;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-box-align: center;
    -ms-flex-align: center;
    -webkit-align-items: center;
    align-items: center;
    margin: 60px 0px;
  }

  & .swiper-button-next {
    background-image: url("/arrowLight.svg");
    border-radius: 50%;
    background-repeat: no-repeat;
    background-position: center;
    width: 48px;
    height: 48px;
    box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
    display: flex;
    align-items: center;
  }

  & .swiper-button-next::after {
    display: none;
  }
  & .swiper-button-prev {
    background-image: url("/Arrowright.svg");
    border-radius: 50%;
    background-repeat: no-repeat;
    background-position: center;
    width: 48px;
    height: 48px;
    box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
  }

  & .swiper-button-prev::after {
    display: none;
  }

  .slider1 {
    background-image: url("slider 1.png");
    width: 1170px;
    height: 524px;
    display: block;
    object-fit: cover;
  }
  .slider1 h1 {
    positsion: relative;
    color: #23272b;
    width: 35%;
    font-weight: 700;
    font-size: 48px;
    line-height: 150%;
    margin-left: 8%;
    margin-top: 10%;
  }
  & .batafsil-btn {
    padding: 16px 30px;
    border: none;
    background-color: #e93235;
    border-radius: 8px;
    color: white;
    margin-left: 8%;
    margin-top: 30px;
  }
  & .facility {
    display: flex;
    margin-bottom: 100px;
  }
  .facility-item h2 {
    font-weight: 500;
    font-size: 20px;
    line-height: 150%;
    color: #143650;
    margin: 24px 0px 16px 0px;
  }
  .facility-item p {
    font-weight: 400;
    font-size: 16px;
    line-height: 150%;
    color: #738da3;
  }
  .facility-item h2,
  .facility-item p,
  .facility-item {
    text-align: center;
  }
  & .facility-image {
    padding: 32px 40px 42px 35px;
    background-color: #f7f8fc;
    border-radius: 50%;
  }
  & .card-item {
    min-width: calc(25% - 24px);
    width: calc(25% - 24px);
    padding: 16px;
    position: relative;
    border-radius: 16px;
    filter: none;
    height: 331px;
    margin: 12px;
  }
  & .cards {
    display: flex;
    overflow-x: scroll;
  }
  & .card-item h5 {
    font-weight: 400;
    font-size: 12px;
    line-height: 14px;
    color: #6f818f;
    height: 30px;
    margin: 10px 0px 0px;
  }
  & .card-item h4 {
    font-weight: 400;
    font-size: 16px;
    line-height: 150%;
    color: #23272b;
    height: 48px;
    line-height: 150%;
    margin: 8px 0px;
  }
  & .card-item button {
    background: #e93235;
    border-radius: 8px;
    padding: 12px 24px;
    color: white;
    border: none;
    width: 100%;
    font-weight: 500;
    font-size: 16px;
    line-height: 19px;
    position:absolute;
  }
  & .cards::-webkit-scrollbar {
    width: 0;
    height: 0;
  }
  @media (max-width: 1100px) {
    .card-item {
      min-width: calc(33.3333% - 24px);
    }
  }
  @media (max-width: 800px) {
    .card-item {
      min-width: calc(50% - 24px);
    }
  }
  @media (max-width: 500px) {
    .card-item {
      min-width: calc(100% - 24px);
    }
  }
`;

export default function Home() {
  const [resultImage, setResultImage] = useState("");
  const [results, setResults] = useState([]);
  useEffect(() => {
    const data = new FormData();
    axios()
      .get("/drug/?per_page=6")
      .then((response) => {
        const data = response?.data?.results;
        const results = Array.isArray(data) ? data : [];
        setResults(results);
        const iterator = data.values();
        for (const value of iterator) {
          const results = value;
          results.Image.map((e) => {
            const resultImage = e.image;
            console.log(resultImage);
            setResultImage(resultImage);
          });
        }
      })
      .catch(() => console.log("err"));
  }, []);

  return (
    <div>
      <Head>
        <title>Internet dorixona - Apotheca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Group.png" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous"
        ></link>
        {/* icon */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <StyleElement>
        <main className="content">
          <div className="container">
            <Swiper
              navigation={true}
              modules={[Navigation]}
              className="mySwiper"
            >
              <SwiperSlide>
                <div className="slider1">
                  <h1>
                    Ваш <span style={{ color: "#E93235" }}>первый шаг</span> к
                    активному долголетию
                  </h1>
                  <button className="batafsil-btn">Подробнее</button>
                </div>
              </SwiperSlide>
              <SwiperSlide>Slide 2</SwiperSlide>
              <SwiperSlide>Slide 3</SwiperSlide>
              <SwiperSlide>Slide 4</SwiperSlide>
            </Swiper>
            <div>
              <div className="facility row">
                <div className="facility-item col-12  col-md-6 col-lg-4">
                  <Image
                    src="/icons-1.svg"
                    className="facility-image"
                    width={145}
                    height={145}
                  />
                  <h2>Широкий выбор ассортиментов</h2>
                  <p>
                    Сайт рыбатекст поможет дизайнеру, верстальщику, вебмастеру
                    сгенерировать несколько абзацев более менее осмысленного
                    текста рыбы на русском.
                  </p>
                </div>
                <div className="facility-item col-12  col-md-6 col-lg-4">
                  <Image
                    src="/icons-2.svg"
                    className="facility-image"
                    width={145}
                    height={145}
                  />
                  <h2>Консультация с экспертами в аптеке</h2>
                  <p>
                    Сайт рыбатекст поможет дизайнеру, верстальщику, вебмастеру
                    сгенерировать несколько абзацев более менее осмысленного
                    текста рыбы на русском.
                  </p>
                </div>
                <div className="facility-item col-12  col-md-6 col-lg-4">
                  <Image
                    src="/icons-3.svg"
                    className="facility-image"
                    width={145}
                    height={145}
                  />
                  <h2>Бронирование и доставка лекарств</h2>
                  <p>
                    Сайт рыбатекст поможет дизайнеру, верстальщику, вебмастеру
                    сгенерировать несколько абзацев более менее осмысленного
                    текста рыбы на русском.
                  </p>
                </div>
              </div>
            </div>
            <div>
              <h2>Maxsus takliflar</h2>
              <div className="cards ">
                {results.map(({ name, Country_of_origin }) => {
                  // console.log(
                  //   <Image src={resultImage} width={130} height={130} />
                  // );
                  return (
                    <div className="card-item ">
                      <Image
                        src={""}
                        width={130}
                        height={130}
                        onError={(e) => {
                          e.target.src =
                            "https://www.svgindianmarket.com/images/thumbs/default-image_510.png"; // some replacement image
                        }}
                      />
                      <div >
                      <h5>{Country_of_origin.name}</h5>
                      <h4>{ name.length<=45 ? name : name.slice(0, 47)+'...'}</h4>
                      <button className="btn">
                        <Image src="/Bag.svg" width={13} height={13} />
                        Savatga qo'shish
                      </button>
                      <i className="fa fa-heart"></i>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </main>
      </StyleElement>
    </div>
  );
}
